;; from exercise 3.3 (with additions)
(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
	(begin (set! balance (- balance amount))
	       balance)
	"Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (add-password new-password)
    (set! passwords (cons new-password passwords))
    '())
  (define passwords (list password))
  (define (dispatch attempted-password m)
    (if (member attempted-password passwords)
	(cond ((eq? m 'withdraw) withdraw)
	      ((eq? m 'deposit) deposit)
	      ((eq? m 'add-password) add-password)
	      (else (error "Unknown request -- MAKE-ACCOUNT"
			   m)))
	(error "Incorrect password")))
  dispatch)

(define (make-joint account password new-password)
  (begin ((account password 'add-password) new-password)
	 account))
